### PR TITLE
Fix live stream stopping

### PR DESCRIPTION
**Pull request by florianrehm**
Fix live stream stopping after some seconds due to missing rtcp sender report

### CODE REVIEW

**Comment by maximkulkin** [comment]
Hi Florian. I appreciate you root causing the issue, however the fix is not what we want. It makes RTCP sender report being sent on every frame, which is way too often. I think proper fix would be to store timestamp of next RTCP sender report (timestamp of last sender report + sender report interval) and sending it whenever we exceed that timestamp.

**Comment by florianrehm** [comment]
Hi, I agree with your statement.
I will invest some more time to figure out the expected interval from mediaserverd and update the pull request.

**Comment by florianrehm** [comment]
Please have a look at the updated pull request.

**Comment by okanduzyel** [comment]
> > > > HomeKit: [Client 57] Resource
> > > > �[0;32mI (505795) esp32_camera: Resource payload: {"image-width":640,"image-height":480,"resource-type":"image"}�[0m
> > > > �[0;31mE (505815) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:�[0m
> > > > �[0;31mE (505815) task_wdt:  - IDLE1 (CPU 1)�[0m
> > > > �[0;31mE (505815) task_wdt: Tasks currently running:�[0m
> > > > �[0;31mE (505815) task_wdt: CPU 0: tiT�[0m
> > > > �[0;31mE (505815) task_wdt: CPU 1: Camera Stream�[0m
> > > > �[0;31mE (505815) task_wdt: Print CPU 0 (current core) backtrace�[0m
> 
> This code triggers WDT. Which value do you prefer? and how can I change it?

Tried to change the value of WTD timer but, it is the same. I closed WDT interrupt under menuconfig but it can still trigger the WDT. I am confused.

**Pull request merged**
